name: Docker build and deploy

on:
  push:
    branches: [ "v2024-prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: olegsvs/aukus:2024-prod

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 2m
          script: docker pull olegsvs/aukus:2024-prod && docker stop aukus_2024_prod || true && docker rm aukus_2024_prod || true && docker run -d --env-file /home/aukus/.env_2024_prod --net=host -v "/home/aukus/2024_prod_uploads":/app/static/uploads --name aukus_2024_prod -it olegsvs/aukus:2024-prod

      - name: Success to discord
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Aukus backend v2024 upload success!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Aukus backend v2024 upload failure!
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Aukus backend upload failure!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
