name: Rollup

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 2m
          script: cd ${{ secrets.APP_PATH }} && git pull && ps -ef | grep 'only_api_app' | awk '{print $2}'  | xargs -r kill -9 && nohup gunicorn 'only_api_app:create_app()'  --log-level debug --workers 1 --bind 127.0.0.1:5000  >> backend.log &
