name: Rollup

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 2m
          script: cd ${{ secrets.APP_PATH }} && git pull && sh restart.sh
      - name: Aukus backend upload success!
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
              severity: info
              details: Aukus backend upload success!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Aukus backend upload failure!
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
              severity: error
              details: Aukus backend upload failure!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
